breaking changes: ["breaking/*"]
bug: ["bug/*", "bugfix/*"]
documentation: ["doc/*", "docs/*", "documentation/*"]
enhancement: ["feature/*", "feat/*"]
fix: ["fix/*", "bugfix/*", "hotfix/*"]
polish: ["polish/*", "styles/*", "lint/*", "refine/*"]
tests: ["tests/*", "test/*"]
