categories:
  - title: "🚀 Features"
    labels:
      - "enhancement"
      - "feature"
      - "support"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "💥 Breaking changes"
    labels:
      - "breaking changes"
  - title: "📦 New dependencies"
    labels:
      - "new dependencies"
      - "dependency"
      - "dependencies"
  - title: "💄 Refines"
    labels:
      - "refine"
  - title: "📘 Documentation"
    labels:
      - "documentation"
  - title: "⚙️ Integrations"
    labels:
      - "integrations"
template: |
  ## Changes

  $CHANGES

  ---

  ### 👽 Contributors
  Our big thanks to:
  $CONTRIBUTORS

  ---

  ### 🏷️ Previous tag
  $PREVIOUS_TAG
